
    export type StatusObject = {
      name: string;
      status: string;
      timestamp: string;
      onlinefor: string | null;
      offlineSince: string | null;
      lastSeen: string | null;
      timesOnline: number;
      firstSeen: Date | null;
      timesOffline: number;
      firstTimestamp :string | null;
      lastSessionDuration: string | null;
    }

    export const statuses: StatusObject[] = [
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "1:35:42",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "1:35:42",
    "timesOnline": 0,
    "firstSeen": "1:35:42",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:35:50",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:35:50",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:35:55",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:35:55",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:1",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:1",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:6",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:6",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:12",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:12",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:18",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:18",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:23",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:23",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:29",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:29",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:34",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:34",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:40",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:40",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:45",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:45",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:51",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:51",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:36:57",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:36:57",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:2",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:2",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:8",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:8",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:13",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:13",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:19",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:19",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:25",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:25",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:30",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:30",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:36",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:36",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:41",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:41",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:47",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:47",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:53",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:53",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:37:58",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:37:58",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:4",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:4",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:9",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:9",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:15",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:15",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:20",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:20",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:26",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:26",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:32",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:32",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:37",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:37",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:43",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:43",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:48",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:48",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:38:54",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:38:54",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:0",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:0",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:5",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:5",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:11",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:11",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:16",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:16",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:22",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:22",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:27",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:27",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:33",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:33",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:39",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:39",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:44",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:44",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:50",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:50",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:39:55",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:39:55",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:1",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:1",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:6",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:6",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:12",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:12",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:18",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:18",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:23",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:23",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:29",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:29",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:34",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:34",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:40",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:40",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:46",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:46",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:51",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:51",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:40:57",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:40:57",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:2",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:2",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:8",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:8",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:14",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:14",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:19",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:19",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:25",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:25",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:30",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:30",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:36",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:36",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:42",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:42",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:47",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:47",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:53",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:53",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:41:58",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:41:58",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:4",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:4",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:9",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:9",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:15",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:15",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:21",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:21",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:26",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:26",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:32",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:32",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:37",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:37",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:43",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:43",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:48",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:48",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:42:54",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:42:54",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:43:0",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:43:0",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:43:5",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:43:5",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:43:11",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:43:11",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "online",
    "timestamp": "1:43:16",
    "onlinefor": "0 seconds",
    "offlineSince": null,
    "lastSeen": "1:43:16",
    "timesOnline": 1,
    "firstSeen": "1:35:50",
    "firstTimestamp": "1:35:31",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  }
];
  