
    export type StatusObject = {
      name: string;
      status: string;
      timestamp: string;
      onlinefor: string | null;
      offlineSince: string | null;
      lastSeen: string | null;
      timesOnline: number;
      firstSeen: Date | null;
      timesOffline: number;
      firstTimestamp :string | null;
      lastSessionDuration: string | null;
    }

    export const statuses: StatusObject[] = [
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:7",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:7",
    "timesOnline": 0,
    "firstSeen": "3:54:7",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:18",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:18",
    "timesOnline": 0,
    "firstSeen": "3:54:18",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:23",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:23",
    "timesOnline": 0,
    "firstSeen": "3:54:23",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:29",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:29",
    "timesOnline": 0,
    "firstSeen": "3:54:29",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:35",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:35",
    "timesOnline": 0,
    "firstSeen": "3:54:35",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:40",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:40",
    "timesOnline": 0,
    "firstSeen": "3:54:40",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:46",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:46",
    "timesOnline": 0,
    "firstSeen": "3:54:46",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:51",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:51",
    "timesOnline": 0,
    "firstSeen": "3:54:51",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:54:57",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:54:57",
    "timesOnline": 0,
    "firstSeen": "3:54:57",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:3",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:3",
    "timesOnline": 0,
    "firstSeen": "3:55:3",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:8",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:8",
    "timesOnline": 0,
    "firstSeen": "3:55:8",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:14",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:14",
    "timesOnline": 0,
    "firstSeen": "3:55:14",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:19",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:19",
    "timesOnline": 0,
    "firstSeen": "3:55:19",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:25",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:25",
    "timesOnline": 0,
    "firstSeen": "3:55:25",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:30",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:30",
    "timesOnline": 0,
    "firstSeen": "3:55:30",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:36",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:36",
    "timesOnline": 0,
    "firstSeen": "3:55:36",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:42",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:42",
    "timesOnline": 0,
    "firstSeen": "3:55:42",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:47",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:47",
    "timesOnline": 0,
    "firstSeen": "3:55:47",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:53",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:53",
    "timesOnline": 0,
    "firstSeen": "3:55:53",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:55:59",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:55:59",
    "timesOnline": 0,
    "firstSeen": "3:55:59",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:4",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:4",
    "timesOnline": 0,
    "firstSeen": "3:56:4",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:10",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:10",
    "timesOnline": 0,
    "firstSeen": "3:56:10",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:15",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:15",
    "timesOnline": 0,
    "firstSeen": "3:56:15",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:21",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:21",
    "timesOnline": 0,
    "firstSeen": "3:56:21",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:27",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:27",
    "timesOnline": 0,
    "firstSeen": "3:56:27",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:32",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:32",
    "timesOnline": 0,
    "firstSeen": "3:56:32",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:38",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:38",
    "timesOnline": 0,
    "firstSeen": "3:56:38",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:43",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:43",
    "timesOnline": 0,
    "firstSeen": "3:56:43",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:49",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:49",
    "timesOnline": 0,
    "firstSeen": "3:56:49",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:56:55",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:56:55",
    "timesOnline": 0,
    "firstSeen": "3:56:55",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:0",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:0",
    "timesOnline": 0,
    "firstSeen": "3:57:0",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:6",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:6",
    "timesOnline": 0,
    "firstSeen": "3:57:6",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:11",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:11",
    "timesOnline": 0,
    "firstSeen": "3:57:11",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:17",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:17",
    "timesOnline": 0,
    "firstSeen": "3:57:17",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:23",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:23",
    "timesOnline": 0,
    "firstSeen": "3:57:23",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:28",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:28",
    "timesOnline": 0,
    "firstSeen": "3:57:28",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:34",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:34",
    "timesOnline": 0,
    "firstSeen": "3:57:34",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:39",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:39",
    "timesOnline": 0,
    "firstSeen": "3:57:39",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:45",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:45",
    "timesOnline": 0,
    "firstSeen": "3:57:45",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:51",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:51",
    "timesOnline": 0,
    "firstSeen": "3:57:51",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:57:56",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:57:56",
    "timesOnline": 0,
    "firstSeen": "3:57:56",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:2",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:2",
    "timesOnline": 0,
    "firstSeen": "3:58:2",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:7",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:7",
    "timesOnline": 0,
    "firstSeen": "3:58:7",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:13",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:13",
    "timesOnline": 0,
    "firstSeen": "3:58:13",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:19",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:19",
    "timesOnline": 0,
    "firstSeen": "3:58:19",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:24",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:24",
    "timesOnline": 0,
    "firstSeen": "3:58:24",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:30",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:30",
    "timesOnline": 0,
    "firstSeen": "3:58:30",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:35",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:35",
    "timesOnline": 0,
    "firstSeen": "3:58:35",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:41",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:41",
    "timesOnline": 0,
    "firstSeen": "3:58:41",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:47",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:47",
    "timesOnline": 0,
    "firstSeen": "3:58:47",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:52",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:52",
    "timesOnline": 0,
    "firstSeen": "3:58:52",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:58:58",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:58:58",
    "timesOnline": 0,
    "firstSeen": "3:58:58",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:3",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:3",
    "timesOnline": 0,
    "firstSeen": "3:59:3",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:9",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:9",
    "timesOnline": 0,
    "firstSeen": "3:59:9",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:15",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:15",
    "timesOnline": 0,
    "firstSeen": "3:59:15",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:20",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:20",
    "timesOnline": 0,
    "firstSeen": "3:59:20",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:26",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:26",
    "timesOnline": 0,
    "firstSeen": "3:59:26",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:32",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:32",
    "timesOnline": 0,
    "firstSeen": "3:59:32",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:37",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:37",
    "timesOnline": 0,
    "firstSeen": "3:59:37",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:43",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:43",
    "timesOnline": 0,
    "firstSeen": "3:59:43",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:48",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:48",
    "timesOnline": 0,
    "firstSeen": "3:59:48",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "3:59:54",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "3:59:54",
    "timesOnline": 0,
    "firstSeen": "3:59:54",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "4:0:0",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "4:0:0",
    "timesOnline": 0,
    "firstSeen": "4:0:0",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "4:0:5",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "4:0:5",
    "timesOnline": 0,
    "firstSeen": "4:0:5",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "4:0:11",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "4:0:11",
    "timesOnline": 0,
    "firstSeen": "4:0:11",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "4:0:16",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "4:0:16",
    "timesOnline": 0,
    "firstSeen": "4:0:16",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "4:0:22",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "4:0:22",
    "timesOnline": 0,
    "firstSeen": "4:0:22",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  },
  {
    "name": "Lianne",
    "status": "Offline",
    "timestamp": "4:0:28",
    "onlinefor": null,
    "offlineSince": "0 seconds",
    "lastSeen": "4:0:28",
    "timesOnline": 0,
    "firstSeen": "4:0:28",
    "firstTimestamp": "3:54:5",
    "lastSessionDuration": "0 seconds",
    "timesOffline": 0
  }
];
  